matrix:
  include:
    - language: c
      compiler: gcc
      script:
        - cd 9cc
        - make
        - ./test.sh

    - language: rust
      script:
        - cd rcc
        - cargo build --verbose --all
        - cargo test --verbose --all

# vim:ft=yaml et ts=2 sw=2:
